# Generated by Django 4.2.7 on 2026-07-23 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0003_iran_market_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='شناسه دستگاه')),
                ('fingerprint_hash', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='هش fingerprint')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='نوع دستگاه')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='سیستم\u200cعامل')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='مرورگر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('is_emulator', models.BooleanField(default=False, verbose_name='شبیه\u200cساز است')),
                ('is_rooted', models.BooleanField(default=False, verbose_name='روت/جیل\u200cبریک')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دستگاه',
                'verbose_name_plural': 'دستگاه\u200cها',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='شناسه مرچنت')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('category', models.CharField(choices=[('RETAIL', 'خرده\u200cفروشی'), ('DIGITAL_GOODS', 'کالای دیجیتال'), ('MARKETPLACE', 'مارکت\u200cپلیس'), ('BNPL_PARTNER', 'همکار BNPL'), ('SERVICES', 'خدمات'), ('OTHER', 'سایر')], default='OTHER', max_length=30, verbose_name='دسته\u200cبندی')),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز ریسک')),
                ('chargeback_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نرخ چارجبک (%)')),
                ('refund_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نرخ بازگشت وجه (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مرچنت',
                'verbose_name_plural': 'مرچنت\u200cها',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='explanation',
            field=models.JSONField(blank=True, default=list, verbose_name='توضیح تصمیم (explainable AI)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_pep',
            field=models.BooleanField(default=False, verbose_name='شخص در معرض خطر سیاسی (PEP)'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('THRESHOLD', 'Threshold-based'), ('PATTERN', 'Pattern-based'), ('BEHAVIORAL', 'Behavioral'), ('GEOGRAPHIC', 'Geographic'), ('PEP', 'PEP — Politically Exposed Person'), ('VELOCITY', 'Velocity — Transaction Frequency'), ('CONCENTRATION', 'Concentration — Same Beneficiary'), ('SANCTIONED', 'Sanctioned Country — Cross-border'), ('NIGHT_WEEKEND', 'Night/Weekend Activity'), ('ROUND_AMOUNT', 'Round-amount / Structuring Pattern'), ('NEW_ACCOUNT', 'New-account Velocity (30/90 days)'), ('DEVICE_SHARING', 'Device Shared Across Accounts'), ('MERCHANT_ABUSE', 'Merchant Fake-purchase / Chargeback Abuse'), ('BNPL_RISK', 'BNPL Default Risk Pattern')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('BNPL_PURCHASE', 'خرید اعتباری (BNPL)'), ('BNPL_REPAYMENT', 'بازپرداخت BNPL')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='aml.device', verbose_name='دستگاه'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='aml.merchant', verbose_name='مرچنت'),
        ),
    ]
