# Generated by Django 4.2.7 on 2026-08-18 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0004_fraud_pivot_didebaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ارجاع'),
        ),
        migrations.AddField(
            model_name='alert',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='بررسی\u200cکننده'),
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('COMMENT', 'یادداشت'), ('ASSIGNMENT', 'ارجاع به بررسی\u200cکننده'), ('STATUS_CHANGE', 'تغییر وضعیت')], default='COMMENT', max_length=20, verbose_name='نوع')),
                ('comment', models.TextField(blank=True, verbose_name='متن یادداشت')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aml.alert', verbose_name='هشدار')),
            ],
            options={
                'verbose_name': 'یادداشت هشدار',
                'verbose_name_plural': 'یادداشت\u200cهای هشدار',
                'ordering': ['-created_at'],
            },
        ),
    ]
