# Generated by Django 4.2.7 on 2026-10-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aml', '0005_alert_assigned_at_alert_assigned_to_alertcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('COUNTRY', 'کشور'), ('ENTITY', 'شخص/نهاد')], default='COUNTRY', max_length=10, verbose_name='نوع')),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2, verbose_name='کد کشور (ISO-2)')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام شخص/نهاد')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='کد/شناسه ملی')),
                ('source_list', models.CharField(blank=True, max_length=100, verbose_name='فهرست منبع')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('added_by', models.CharField(blank=True, max_length=100, verbose_name='ثبت\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مورد فهرست پایش',
                'verbose_name_plural': 'فهرست پایش (تحریم/ممنوعیت)',
                'ordering': ['entry_type', 'country_code', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='aml_alert_alert_i_9f51ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='aml_alert_created_a5a522_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='aml_auditlo_timesta_ed7e12_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='aml_auditlo_path_3c9985_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='aml_auditlo_user_042343_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='aml_custome_custome_ac9733_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='aml_custome_email_8ff208_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='aml_report_report__85e117_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='aml_transac_transac_056293_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='aml_transac_transac_7f86a7_idx',
        ),
        migrations.AlterField(
            model_name='thresholdconfig',
            name='threshold_type',
            field=models.CharField(choices=[('TRANSACTION_AMOUNT', 'حد مبلغ تراکنش'), ('DAILY_AMOUNT', 'حد مبلغ روزانه'), ('DAILY_COUNT', 'حد تعداد روزانه'), ('CROSS_BORDER_AMOUNT', 'حد تراکنش بین\u200cالمللی'), ('STRUCTURING_AMOUNT', 'حد تشخیص تجزیه (Structuring)'), ('CTR_THRESHOLD', 'آستانه گزارش تراکنش کلان (CTR)'), ('SAR_RISK_SCORE', 'آستانه گزارش تراکنش مشکوک (SAR)'), ('ALERT_SLA_HOURS', 'مهلت رسیدگی به هشدار ارجاع\u200cشده (ساعت)')], max_length=50, verbose_name='نوع آستانه'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'created_at'], name='aml_alert_status_8c7afc_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'assigned_at'], name='aml_alert_status_acae18_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['assigned_to', 'status'], name='aml_alert_assigne_06adeb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='aml_auditlo_user_5d3c29_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status_code', 'timestamp'], name='aml_auditlo_status__7d46e6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'transaction_type', 'transaction_date'], name='aml_transac_custome_b87877_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'receiver_account'], name='aml_transac_custome_448879_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['device', 'transaction_date'], name='aml_transac_device__88326d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['merchant', 'transaction_date'], name='aml_transac_merchan_a4308c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='aml_transac_status_4397fa_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistentry',
            index=models.Index(fields=['is_active', 'entry_type'], name='aml_watchli_is_acti_fe8ff4_idx'),
        ),
    ]
